name: Run checks

on:
  push:
    branches:
    - main
    paths:
    - '**.swift'
  pull_request:
    branches:
    - main

jobs:

  run-checks:
    # runs-on: macOS-latest
    runs-on: self-hosted
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Install Dependencies
      run: |
        brew install mint
        mint install NickLockwood/SwiftFormat@0.53.4 --no-link
    
    - name: run script
      run: ./scripts/run-checks.sh

  run-check-api-breakage:
    # runs-on: macOS-latest
    runs-on: self-hosted
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: run script
      run: |
        ./scripts/check-api-breakage.sh
        cat api-breakage-output.log >> $GITHUB_STEP_SUMMARY

    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        message: |
          Hello world ! :wave:
      

    # - name: Get log
    #   id: vars
    #   run: echo "log=$(cat api-breakage-output.log)" >> $GITHUB_OUTPUT
      
    # - name: Print log
    #   run: echo ${{ steps.vars.outputs.log }}

    # - name: Add comment
    #   uses: mshick/add-pr-comment@v2
    #   with:
    #     message-path: |
    #       api-breakage-output.log
